### ISSUE TITLE
Cuda support?

### ISSUE THREAD

**Issue by shelldandy** [Benjamin-Dobell/nvidia-update#22]
Asking wether this package does cuda as well.

If not, what would be the procedure for it? Normal install?

Thanks!

**Comment by Benjamin-Dobell** [comment]
No CUDA at present, it works fine though if you just follow the normal CUDA install procedure.

I did briefly look into adding it in but it's a bit of a pain because CUDA versions don't necessarily match specific driver versions. Also, to my knowledge, all the CUDA releases have had reasonable performance so there's no real need to maintain a CUDA blacklist.

**Comment by shelldandy** [comment]
Gotcha, thanks for the info
