### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by anonymouz4** [Benjamin-Dobell/nvidia-update#8]
How do I know when a new version, that is not blacklisted, is available?
Or does this script automatically check for updates?

**Comment by Benjamin-Dobell** [comment]
Because this script installs the NVIDIA Driver Manager, it'll actually prompt you when a new driver is available.

Then simply run this script again. It'll either download the latest version, or inform you you're already on the latest version (which will happen if the newer version has been blacklisted).
